
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-container
    ports:
      - "9411:9411"
    networks:
      - microservices-network

  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    container_name: service-discovery-container
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://localhost:9296
    networks:
      - microservices-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service-container
    ports:
      - "8700:8700"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://localhost:9296
    networks:
      - microservices-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service-container
    ports:
      - "8500:8500"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://localhost:9296
    networks:
      - microservices-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service-container
    ports:
      - "8300:8300"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://localhost:9296
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge



