# Monitoring passcode requerido
monitoringPasscode: "monitoring123"

# Usar SonarQube Community Edition (gratuita)
community:
  enabled: true

service:
  type: NodePort
  externalPort: 9000
  internalPort: 9000
  nodePort: 30900

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"

# PostgreSQL como base de datos
postgresql:
  enabled: true
  auth:
    username: sonarqube
    password: sonarqube123
    database: sonarqube
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

# Configuración de JVM para SonarQube
jvmOpts: "-Xmx2g -Xms1g"

# Plugins adicionales (opcional)
plugins:
  install:
    - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/5.0.0/sonar-dependency-check-plugin-5.0.0.jar"

# Configuración inicial
account:
  adminPassword: admin123
  currentAdminPassword: admin
