apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: ecommerce
  labels:
    app: service-discovery
spec:
  type: NodePort
  selector:
    app: service-discovery
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30761
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: ecommerce
  labels:
    app: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: service-discovery:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_CONFIG_IMPORT
          value: ""
        - name: SPRING_JPA_SHOW_SQL
          value: "false"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
          value: "WARN"
        - name: LOGGING_LEVEL_ORG_HIBERNATE
          value: "WARN"
        - name: SPRING_MAIN_LAZY_INITIALIZATION
          value: "true"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        resources:
          requests:
            memory: "768Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 60
          timeoutSeconds: 5
